baseURL = "https://KimYangOfCat.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
title = "Kim`s Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "LeaveIt" # 主题 (需要自己下载)
paginate = 10 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "UA-150383643-1" # Google 统计 id
preserveTaxonomyNames = true
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
[Permalinks]
 posts = "/:year/:filename/"
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[params]
    since = 2019
    author = "Kim Yang"                          # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "Never give up!"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "/about" # post or other
    enableGitalk = false # gitalk 评论系统
    google_verification = ""
    description = "Blog" # (Meta) 描述
    keywords = "KimYang" # site keywords
    beian = ""
    baiduAnalytics = ""
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
[params.social]
    GitHub = "KimYangOfCat"
    # Twitter = "sxxx"
    Email  = "kim_yang95@163.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    #Telegram = "xxoo"
    # Dribbble = "xxoo"
     #Medium = "xxoo"
[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin= "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.